server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${COLLA_MAIL}
    password: ${COLLA_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 실운영은 validate or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

gcp:
  service-account:
    path: service-account.json